version: '2'

services:
  web:
    depends_on:
      - 'auth_app'
      - 'client_app'
    build: 
      context: ./tbproxy
    ports:
      - '80:80'
    volumes:
      - 'auth_public:/static/auth'
      - 'client_public:/static/client'
 
  auth_app:
    depends_on:
      - 'database'
    build: 
      context: ./tbauth
    expose:
      - '9000'
    volumes:
      - './tbauth:/tbauth'
      - 'auth_public:/tbauth/public'
    env_file:
      - 'prod.env'
      - 'auth.env'

  client_app:
    depends_on:
      - 'database'
      - 'redis'
    build: 
      context: ./tbclient
    expose:
      - '9000'
    volumes:
      - './tbclient:/tbclient'
      - 'client_public:/tbclient/public'
    env_file:
      - 'prod.env'
      - 'client.env'

  database:
    image: 'postgres:alpine'
    env_file:
      - 'prod.env'
    expose:
      - '5432'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  redis:
    image: 'redis:3.2-alpine'
    command: redis-server --requirepass p4ssw0rd
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/var/lib/redis/data'

volumes:
  redis:
  postgres:
  auth_public:
  client_public:
